# Generated by Django 2.2.7 on 2019-12-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anwser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(default='', max_length=128)),
                ('anwser', models.CharField(default='', max_length=10000)),
                ('anwser_time', models.CharField(default='', max_length=128)),
                ('respondent_level', models.CharField(default='', max_length=128)),
                ('respondent_id', models.CharField(default='', max_length=128)),
                ('star', models.CharField(default='', max_length=128)),
                ('star_guy', models.CharField(default='', max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='uodate_time')),
            ],
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=200)),
                ('file_name', models.FileField(upload_to='case/%Y/%m/%d/', verbose_name='file_name')),
            ],
            options={
                'verbose_name': 't1',
                'verbose_name_plural': 't2',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('name_code', models.CharField(default='', max_length=200)),
                ('credit', models.CharField(default='', max_length=200)),
                ('credit_for_exp', models.CharField(default='0', max_length=200)),
                ('hours_per_week', models.CharField(default='', max_length=200)),
                ('Opening_semester', models.CharField(default='', max_length=200)),
                ('recommended_Opening_semester', models.CharField(default='', max_length=200)),
                ('language', models.CharField(default='', max_length=200)),
                ('prerequisite_courses', models.CharField(default='', max_length=200)),
                ('department', models.CharField(default='', max_length=200)),
                ('replace_course', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('code', models.CharField(default='', max_length=16)),
                ('description', models.CharField(default='', max_length=128)),
                ('url_in_sustc', models.CharField(default='', max_length=128)),
                ('college', models.CharField(default='', max_length=128)),
                ('id_f', models.CharField(default='', max_length=128)),
                ('level', models.CharField(default='1', max_length=128)),
                ('super', models.CharField(default='0', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='firewall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('process', models.CharField(default='', max_length=200)),
                ('local_ip', models.CharField(default='', max_length=200)),
                ('local_port', models.CharField(default='', max_length=200)),
                ('remote_ip', models.CharField(default='', max_length=200)),
                ('remote_port', models.CharField(default='', max_length=200)),
                ('protocol', models.CharField(default='', max_length=200)),
                ('direction', models.CharField(default='', max_length=200)),
                ('action', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=200)),
                ('enalbled', models.CharField(default='', max_length=200)),
                ('profile', models.CharField(default='', max_length=400)),
                ('redirect_ip', models.CharField(default='', max_length=40)),
                ('redirect_port', models.CharField(default='', max_length=40)),
                ('content_all1', models.CharField(default='', max_length=400)),
                ('add_time', models.CharField(default='', max_length=400)),
                ('last_change', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='General_knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(default='', max_length=512)),
                ('credit_min', models.CharField(default='', max_length=512)),
                ('credit_min_gk', models.CharField(default='', max_length=512)),
                ('credit_min_pe', models.CharField(default='', max_length=512)),
                ('credit_min_el', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('id_f', models.CharField(default='', max_length=128)),
                ('operation', models.CharField(default='', max_length=16)),
                ('user', models.CharField(default='', max_length=128)),
                ('befor', models.CharField(default='', max_length=512)),
                ('after', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='log_b',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('id_f', models.CharField(default='', max_length=128)),
                ('operation', models.CharField(default='', max_length=16)),
                ('user', models.CharField(default='', max_length=128)),
                ('befor', models.CharField(default='', max_length=512)),
                ('after', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questioner', models.CharField(default='', max_length=128)),
                ('title', models.CharField(default='', max_length=10000)),
                ('question', models.CharField(default='', max_length=10000)),
                ('question_time', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='order')),
                ('name', models.CharField(default='', max_length=20, verbose_name='title')),
                ('content', models.CharField(default='', max_length=1000, verbose_name='content')),
            ],
            options={
                'verbose_name': 'rule',
                'verbose_name_plural': 'rule',
                'db_table': 'tb_Rule',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('level', models.CharField(default='', max_length=10)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(default='', max_length=128)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='var',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
