# Generated by Django 2.2.7 on 2019-12-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0003_auto_20191225_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questioner', models.CharField(default='', max_length=128)),
                ('title', models.CharField(default='', max_length=10000)),
                ('question', models.CharField(default='', max_length=10000)),
                ('question_time', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
