# Generated by Django 2.2.7 on 2019-12-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0004_question_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.EmailField(default='', max_length=10000),
        ),
    ]
